-- CREATING THE DATABASE 
CREATE DATABASE HR_PROJECT;

-- Attrition analysis

-- 1. WHAT IS THE OVERALL EMPLOYEE ATTRITION RATE?
SELECT 
	ROUND((COUNT(CASE WHEN ATTRITION='YES' THEN 1 END)*100)/COUNT(*),2) AS ATTRITION_RATE
FROM HR_DATA;
-- INSIGHT: THE OVERALL ATTRITION RATE(%) IS 16.12 

-- 2. WHICH DEPARTMENT HAS THE HIGHEST ATTRITION RATE?
SELECT DEPARTMENT, 
	ROUND((COUNT(CASE WHEN ATTRITION='YES' THEN 1 END)*100)/COUNT(*),2) AS ATTRITION_RATE
FROM HR_DATA
GROUP BY DEPARTMENT
ORDER BY ATTRITION_RATE;
-- INSIGHT: THE SALES DEPARTMENT HAS THE HIGHEST ATTRITION RATE OF 20.63%. 

-- 3. DOES WORKING OVERTIME AFFECT ATTRITION?
SELECT OVERTIME, COUNT(*) AS TOTAL_EMPLOYEES,
COUNT(CASE WHEN ATTRITION = 'YES' THEN 1 END) AS EMPLOYEES_LEFT,
ROUND((COUNT(CASE WHEN ATTRITION='YES' THEN 1 END)*100)/COUNT(*),2) AS ATTRITION_RATE
FROM HR_DATA
GROUP BY OVERTIME
ORDER BY ATTRITION_RATE DESC;
-- INSIGHT: THE ATTRITION RATE OF EMPLOYEES WHO WORKED OVERTIME IS 30.53% WHICH IS ALMOST THREE TIMES OF THE EMPLOYEES WHO DIDNT WORK OVERTIME. 
            -- SO ITS EVIDENT THAT OVERTIME WORK AFFECTS ATTRITION.

-- 4. WHICH JOBROLES LOST THE MOST NUMBER OF EMPLOYEES?
SELECT JOBROLE, COUNT(*) AS TOTAL_EMPLOYEES,
COUNT(CASE WHEN ATTRITION = 'YES' THEN 1 END) AS EMPLOYEES_LEFT,
ROUND((COUNT(CASE WHEN ATTRITION='YES' THEN 1 END)*100)/COUNT(*),2) AS ATTRITION_RATE
FROM HR_DATA
GROUP BY JOBROLE
ORDER BY ATTRITION_RATE DESC;
-- INSIGHT: SALES REPRESENTATIVE HAS THE HIGHEST ATTRITION RATE OF 39.76% FOLLOWED BY LAB TECHNICIAN 23.94% AND HUMAN RESOURCE 23.08%.



-- SALARY AND COMPENSATION

-- 5. WHAT IS THE AVERAGE SALARY PER JOB ROLE AND DEPARTMENT?
SELECT JOBROLE,DEPARTMENT, AVG(MONTHLYINCOME) AS AVG_SALARY
FROM HR_DATA
GROUP BY JOBROLE,DEPARTMENT
ORDER BY AVG_SALARY DESC;
-- INSIGHT: ON AN AVERAGE THE MANAGERS ACROSS ALL DEPARTMENTS EARNS THE MOST WHERE AS THE SALES REPRESENTATIVES EARN THE LEAST ON AN AVERAGE

-- 6. ARE EMPLOYEES WHO LEAVE PAID LESS THAN THOSE EMPLOYEES WHO STAY
SELECT ATTRITION, AVG(MONTHLYINCOME) AS AVG_SALARY
FROM HR_DATA
GROUP BY ATTRITION;
-- INSIGHT: THE AVERAGE SALARY OF EMPLOYEES WHO LEFT IS LESS THAN THE AVERAGE INCOME OF EMPLOYEES WHO STAYED

-- 7. DOES JOB SATISFACTION DEPEND ON SALARY?
SELECT JOBSATISFACTION, AVG(MONTHLYINCOME) AS AVERAGE_SALARY
FROM HR_DATA
GROUP BY JOBSATISFACTION 
ORDER BY JOBSATISFACTION;
-- INSIGHT: THE AVERAGE SALARY OF EMPLOYEES ARE VERY CLOSE TO EACH OTHER ACROSS ALL JOB SATISFACTION LEVELS.
--          SO SALARY MAY NOT BE THE ONLY FACTOR AFFECTING JOB SATISFACTION. WORK LIFE BALANCE, OVERTIME WORK, ENVIRONMENT CAN ALSO CONTRIBUTE. 

-- 8.  DO THE EMPLOYEES WORK OVERTIME GET MORE SALARY THAN THOSE EMPLOYEES WHO DOESNT WOEK OVERTIME?
SELECT OVERTIME, AVG(MONTHLYINCOME) 
FROM HR_DATA
GROUP BY OVERTIME;
-- INSIGHT: EMPLOYEES DOING OVERTIME ARE PAID A LITTLE HIGHER THAN THOSE NOT DOING OVERTIME, BUT THE GAP IS NOT SIGNIFICANT. 
--          THIS INDICATES SALARY IS LIKELY INFLUENCED MORE BY JOB ROLE, EXPERIENCE, OR JOB LEVEL RATHER THAN OVERTIME ALONE.
 


-- EMPLOYEE SATISFACTION AND ENGAGEMENT

-- 9. WHAT IS THE AVERAGE WORK LIFE BALANCE OF EMPLOYEES WHO LEFT VS WHO STAYED?
SELECT ATTRITION, AVG(WORKLIFEBALANCE) AS AVERAGE_WORK_LIFE_BALANVCE
FROM HR_DATA
GROUP BY ATTRITION;
-- INSIGHT: THE AVERAGE WORK LIFE BALANCE OF EMPLOYEES WHO LEFT VS STAYED IS VERY CLOSE TO EACH OTHER, WHICH INDICATES OTHER FACTORS HAVE IMPACT ON ATTRITION AS WELL.

-- 10. WHAT IS THE AVERAGE JOB SATISFACTION SCORE IN EACH DEPARTMENT?
SELECT DEPARTMENT, AVG(JOBSATISFACTION) AS AVG_JOB_SATISFACTION
FROM HR_DATA
GROUP BY DEPARTMENT
ORDER BY AVG_JOB_SATISFACTION DESC;
-- INSIGHT: THE AVERAGE JOB SATISFACTION ACROSS ALL DEPARTMENTS ARE VERY CLOSE TO EACH OTHER, WHERE SALES DEPARTMENT HAS THE HIGHEST AVERAGE JOB SATISFACTION. 

-- 11. HOW MANY EMPLOYEES ARE WELL SATISFIED TO WORK IN THE COMPANY?
SELECT JOBSATISFACTION AS JOB_SATISFACTION_SCORE,COUNT(*) AS TOTAL_EMPLOYEE
FROM HR_DATA
GROUP BY JOBSATISFACTION
ORDER BY JOBSATISFACTION DESC;
-- INSIGHT: IN THE COMPANY MOST OF THE EMPLOYEES ARE WELL SATISFIED WITH THE JOB. 459, EMPLOYEES HAS SCORE OF 4 AND 422 EMPLOYEES HAVE SCORE OF 3.

-- 12. WHAT IS THE ATTRITION RATE IN EACH JOB SATISFACTION LEVEL?
SELECT JOBSATISFACTION, 
	ROUND((COUNT(CASE WHEN ATTRITION='YES' THEN 1 END)*100)/COUNT(*),2) AS ATTRITION_RATE
FROM HR_DATA
GROUP BY JOBSATISFACTION
ORDER BY JOBSATISFACTION DESC;
-- INSIGHT: THE ATTRITION RATE IS LOWER AS THE JOB SATISFACTION INCREASES, WHICH MEANS EMPLOYEES WHO ARE HAVING HIGHER JOB SATISFACTION SCORE ARE LESS LIKELY TO LEAVE THE COMPANY.

-- 13. WHAT IS THE ATTRITION RATE BY ENVIRONMENT SATISFACTION LEVEL?
SELECT ENVIRONMENTSATISFACTION AS ENVIROMENT_SATISFACTION, 
	ROUND((COUNT(CASE WHEN ATTRITION='YES' THEN 1 END)*100)/COUNT(*),2) AS ATTRITION_RATE
FROM HR_DATA
GROUP BY ENVIRONMENTSATISFACTION
ORDER BY ENVIRONMENTSATISFACTION DESC;
-- INSIGHT: THE EMPLOYEES WITH THE HIGHEST EMVIRONMENT SATISFACTION LEVEL OF 4 HAVE THE LEAST ATTRITION RATE OF 13.45%
--          WHERE AS EMPLOYEES WHO ARE NOT SATISFIED WITH ENVIRONMENT WITH SCORE 1 HAVE HIGHEST ATTRITION RATE OF 25.35%.

-- 14. WHAT IS THE TOTAL NUMBER OF HIGH RISK EMPLOYEES?
SELECT DEPARTMENT,COUNT(*) AS HIGH_RISK_EMPLOYEES
FROM HR_DATA
WHERE JOBSATISFACTION=1
	AND ENVIRONMENTSATISFACTION=1
    AND WORKLIFEBALANCE=1
GROUP BY DEPARTMENT;
-- INSIGHT: THERE IS 5 EMPLOYEES WHO FALLS INTO THE HIGH RISK CATEGORY, 4 FROM THE RESEARCH AND DEVELOPMENT DEPARTMENT AND 1 FROM SALES.



-- DEMOGRAPHICS AND DIVERSITY


-- 15. WHAT IS THE GENDER SPLIT ACROSS ALL DEPARTMENTS?
SELECT DEPARTMENT, 
	COUNT(CASE WHEN GENDER='MALE' THEN 1 END) AS NUMBER_OF_MALE_EMPLOYEES,
    COUNT(CASE WHEN GENDER='FEMALE' THEN 1 END) AS NUMBER_OF_FEMALE_EMPLOYEES
FROM HR_DATA
GROUP BY DEPARTMENT;
-- INSIGHT: THE NUMBER MALE EMPLOYEES IS MORE IN GENERAL THAN THE FEMALE EMPLOYEES.

-- 16. WHICH MARIETAL STATUS GROUP HAS THE HIGHEST ATTRITION RATE?
SELECT MARITALSTATUS, 
	ROUND((COUNT(CASE WHEN ATTRITION='YES' THEN 1 END)*100)/COUNT(*),2) AS ATTRITION_RATE
FROM HR_DATA
GROUP BY MARITALSTATUS;
-- INSIGHT: THE ATTRITION RATE OF UNMARRIED EMPLOYEES (25.53%) IS ALMOST 2.5 TIMES THAN THAT OF THOSE EMPLOYEES WHO ARE DIVORCED (10.09)
--           AND ALMOST 2 TIMES OF THE EMPLOYEES WHO ARE MARRIED(12.48%).



-- CAREER GROWTH AND TENURE


-- 17. DO EMPLOYEES WHO HAVE NOT BEEN PROMOTES IN 3+ YEAR LEAVE MORE ?
SELECT 
	CASE 
		WHEN YEARSSINCELASTPROMOTION<3 THEN "LESS THAN 3 YEARS"
        ELSE "3+ YEARS"
	END AS PROMOTION_GROUP,
	COUNT(*) AS TOTAL_EMPLOYEES,
    COUNT(CASE WHEN ATTRITION='YES' THEN 1 END) AS EMPLOYEES_LEFT,
    ROUND((COUNT(CASE WHEN ATTRITION='YES' THEN 1 END)*100)/COUNT(*),2) AS ATTRITION_RATE
FROM HR_DATA
GROUP BY PROMOTION_GROUP;
-- INSIGHT:  ATTRITION RATES WERE FAIRLY SIMILAR ACROSS BOTH PROMOTION GROUPS, INDICATING THAT PROMOTION DELAY MAY NOT HAVE A MAJOR IMPACT ON EMPLOYEE TURNOVER.   


-- 18. WHAT IS THE AVERAGE YEAR SINCE LAST PROMOTION IN EACH DEPARTMENT?
SELECT DEPARTMENT, 
       ROUND(AVG(YEARSSINCELASTPROMOTION), 2) AS AVG_YEARS_NO_PROMOTION 
FROM HR_DATA 
GROUP BY DEPARTMENT 
ORDER BY AVG_YEARS_NO_PROMOTION DESC;
-- INSIGHT: THE SALES DEPARTMENT SHOWS THE LONGEST AVERAGE DURATION WITHOUT PROMOTION, INDICATING POSSIBLE SLOWER CAREER PROGRESSION COMPARED TO OTHER DEPARTMENTS.


-- 19. DO EMPLOYEES WITH MORE COMPANIES WORKED LEAVE MORE OFTEN?
SELECT NUMCOMPANIESWORKED, 
       COUNT(*) AS TOTAL, 
       ROUND((COUNT(CASE WHEN ATTRITION='YES' THEN 1 END)*100)/COUNT(*),2) AS ATTRITION_RATE 
FROM HR_DATA 
GROUP BY NUMCOMPANIESWORKED 
ORDER BY ATTRITION_RATE DESC;
-- INSIGHT: EMPLOYEES WHO HAVE WORKED AT 5 OR MORE COMPANIES SHOW SIGNIFICANTLY HIGHER ATTRITION RATES (PEAKING AT 25.40%), 
--          INDICATING THAT HISTORICAL JOB-HOPPING BEHAVIOR IS A STRONG PREDICTOR OF FUTURE TURNOVER.


-- 20. -- 3. WHICH JOB LEVEL HAS THE LOWEST PROMOTION RATE?
SELECT JOBROLE, 
       ROUND(AVG(YEARSSINCELASTPROMOTION), 2) AS AVG_WAIT_PROMOTION, 
       ROUND(AVG(YEARSATCOMPANY), 2) AS AVG_TENURE 
FROM HR_DATA 
GROUP BY JOBROLE 
ORDER BY JOBROLE;
-- INSIGHT: MANAGERS AND RESEARCH DIRECTORS WAIT THE LONGEST FOR PROMOTIONS DUE TO STRUCTURAL BOTTLENECKS AT LEADERSHIP LEVELS, WHILE ENTRY-LEVEL SALES 
--          AND HR ROLES EXPERIENCE THE FASTEST CAREER VELOCITY.


-- TOP FINDINGS FROM THE ANALYSIS 
-- 1. OVER-TIME IMPACT: OVER TIME WORK ADVERSELY AFFECTS ATTRITION RATE TO THE EXTENT THAT THE ATTRITION RATE OF EMPLOYEES WHO WORKED OVERTIME 
--    IS ALMOST 3 TIMES THE EMPLOYEES WHO DIDNT WOR OVERTIME.

-- 2. JOB SATISFACTION: SALARY WAS NOT THE KEY DECISING FACTOR FOR JOB SATISFACTION, INDICATING  OTHER FACTORS SUCH AS WORK LIFE BALANCE, ENVIRONMENT SATISFACTION HAS AN IMPACT AS WELL 

-- 3. JOB SWITCH IMPACT: EMPLOYEES WHO TEND TO SWITCH JOBS MORE OFTEN HAS HIGHER ATTRITION RATE. 

